#!/bin/sh

#
# Environment variables
#

ORACLE_BASE=/u01/app/oracle; export ORACLE_BASE
ORACLE_HOME=$ORACLE_BASE/product/11.2.0/dbhome_1; export ORACLE_HOME
ORACLE_SID=s225088; export ORACLE_SID
NLS_LANG=RUSSIAN_CIS.AL32UTF8; export NLS_LANG

ORADATA=/u01/avy64; export ORADATA
DB_NAME=loudsoup; export DB_NAME
DB_PASSWORD='123456'; export DB_PASSWORD

LD_LIBRARY_PATH=$ORACLE_HOME/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
PATH=$ORACLE_HOME/bin:$PATH; export PATH
